/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;
import org.demo.entity.Badge;
import org.demo.repository.BadgeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 * Service implementation for Badge.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Service
public class BadgeServiceImpl implements BadgeService {

	@Autowired
	private BadgeRepository badgeRepository;

	@Override
	public Page<Badge> search(Pageable pageable) {
		return badgeRepository.findAll(pageable);
	}

	@Override
	public Badge get(Integer badgeNumber) {
		return badgeRepository.findOne(badgeNumber);
	}

	@Override
	public Boolean delete(Integer badgeNumber) {
		if (badgeRepository.findOne(badgeNumber) != null) {
			badgeRepository.delete(badgeNumber);
			return true;
		}
		return false;
	}

	@Override
	public Badge create(Badge badge) {
		return badgeRepository.save(badge);
	}

	@Override
	public Boolean save(Badge badge) {
		final Integer pk = badge.getBadgeNumber();
		if (badgeRepository.findOne(pk) != null) {
			badgeRepository.save(badge);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(Badge badge) {
		return badgeRepository.exists(badge.getBadgeNumber());
	}


}
