/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.apache.commons.lang3.StringUtils;
import org.demo.entity.Book;
import org.demo.repository.BookRepository;
import org.demo.service.criteria.BookCriteria;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

/**
 * Service implementation for Book.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Service
public class BookServiceImpl implements BookService {

	@Autowired
	private BookRepository bookRepository;

	@Override
	public Page<Book> search(Pageable pageable, BookCriteria criteria) {
		return bookRepository.findAll(new BookSpecification(criteria), pageable);
	}

	@Override
	public Book get(Integer id) {
		return bookRepository.findOne(id);
	}

	@Override
	public Boolean delete(Integer id) {
		if (bookRepository.findOne(id) != null) {
			bookRepository.delete(id);
			return true;
		}
		return false;
	}

	@Override
	public Book create(Book book) {
		return bookRepository.save(book);
	}

	@Override
	public Boolean save(Book book) {
		final Integer pk = book.getId();
		if (bookRepository.findOne(pk) != null) {
			bookRepository.save(book);
			return true;
		}
		return false;
	}

	@Override
	public Boolean exist(Book book) {
		return bookRepository.exists(book.getId());
	}

	class BookSpecification implements Specification<Book> {

		private BookCriteria criteria;

		public BookSpecification(BookCriteria criteria) {
			this.criteria = criteria;
		}

		@Override
		public Predicate toPredicate(Root<Book> root, CriteriaQuery<?> query, CriteriaBuilder builder) {
			final List<Predicate> predicates = new ArrayList<>();
			if (StringUtils.isNotBlank(criteria.getIsbn())) {
				predicates.add(builder.like(builder.lower(root.get("isbn")),
						criteria.getIsbn().toLowerCase() + "%"));
			}
			if (StringUtils.isNotBlank(criteria.getTitle())) {
				predicates.add(builder.like(builder.lower(root.get("title")),
						criteria.getTitle().toLowerCase() + "%"));
			}
			return andTogether(predicates, builder);
		}

		private Predicate andTogether(List<Predicate> predicates, CriteriaBuilder builder) {
			return builder.and(predicates.toArray(new Predicate[0]));
		}
	}

}
