/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Author search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AuthorCriteria {

    private String firstName; 
    private String lastName; 
	// Constructor
	public AuthorCriteria() {
		// Needed empty constructor for serialization
	}

	public void setFirstName(String firstName) {this.firstName = firstName;}
	public String getFirstName() {return this.firstName;}
	public void setLastName(String lastName) {this.lastName = lastName;}
	public String getLastName() {return this.lastName;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(firstName); 
		sb.append("|"); 
		sb.append(lastName); 
        return sb.toString();
	}
}
