/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.resource;

import org.springframework.hateoas.ResourceSupport;

/**
 * Hateoas resource associated with Author.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class AuthorResource extends ResourceSupport {

	// Because id is reserved in parent class, we can't override the getter.
	@SuppressWarnings("unused")
    private Integer id;  
    private String firstName;  
    private String lastName;  

	// Constructor
	public AuthorResource() {
		// Needed empty constructor for serialization
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getFirstName() {
		return this.firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return this.lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
}
