/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.resource;

import org.springframework.hateoas.ResourceSupport;

/**
 * Hateoas resource associated with EmployeeGroup.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class EmployeeGroupResource extends ResourceSupport {

    private String employeeCode;  
    private Short groupId;  

	// Constructor
	public EmployeeGroupResource() {
		// Needed empty constructor for serialization
	}

	public String getEmployeeCode() {
		return this.employeeCode;
	}
	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}
	public Short getGroupId() {
		return this.groupId;
	}
	public void setGroupId(Short groupId) {
		this.groupId = groupId;
	}
}
