/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.CustomerResource;
import org.demo.entity.Customer;

import fr.xebia.extras.selma.Mapper;

/**
 * CustomerResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface CustomerMapper {

	// This will build a fresh new CustomerResource with in infos
	CustomerResource map(Customer in);

	Customer map(CustomerResource in);

	// This will update the given Author
	Customer map(CustomerResource in, Customer out);

	// this will build a fresh list of CustomerResource with in infos
	List<CustomerResource> map(List<Customer> in);
}
