/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.EmployeeGroupResource;
import org.demo.entity.EmployeeGroup;

import fr.xebia.extras.selma.Mapper;

/**
 * EmployeeGroupResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface EmployeeGroupMapper {

	// This will build a fresh new EmployeeGroupResource with in infos
	EmployeeGroupResource map(EmployeeGroup in);

	EmployeeGroup map(EmployeeGroupResource in);

	// This will update the given Author
	EmployeeGroup map(EmployeeGroupResource in, EmployeeGroup out);

	// this will build a fresh list of EmployeeGroupResource with in infos
	List<EmployeeGroupResource> map(List<EmployeeGroup> in);
}
