/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.PublisherResource;
import org.demo.entity.Publisher;

import fr.xebia.extras.selma.Mapper;

/**
 * PublisherResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface PublisherMapper {

	// This will build a fresh new PublisherResource with in infos
	PublisherResource map(Publisher in);

	Publisher map(PublisherResource in);

	// This will update the given Author
	Publisher map(PublisherResource in, Publisher out);

	// this will build a fresh list of PublisherResource with in infos
	List<PublisherResource> map(List<Publisher> in);
}
