/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.mapper;

import java.util.List;

import org.demo.controller.resource.ShopResource;
import org.demo.entity.Shop;

import fr.xebia.extras.selma.Mapper;

/**
 * ShopResource's Mapper declaration using selma.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Mapper(withIgnoreFields = { "id", "links" })
public interface ShopMapper {

	// This will build a fresh new ShopResource with in infos
	ShopResource map(Shop in);

	Shop map(ShopResource in);

	// This will update the given Author
	Shop map(ShopResource in, Shop out);

	// this will build a fresh list of ShopResource with in infos
	List<ShopResource> map(List<Shop> in);
}
