/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.BookOrderItemController;
import org.demo.controller.mapper.BookOrderItemMapper;
import org.demo.controller.resource.BookOrderItemResource;
import org.demo.entity.BookOrderItem;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class BookOrderItemResourceAssembler extends ResourceAssemblerSupport<BookOrderItem, BookOrderItemResource> {

	// declare the mapper
	private BookOrderItemMapper bookOrderItemMapper;

	public BookOrderItemResourceAssembler() {
		super(BookOrderItemController.class, BookOrderItemResource.class);
		bookOrderItemMapper = Selma.builder(BookOrderItemMapper.class).build();
	}

	@Override
	public BookOrderItemResource toResource(BookOrderItem bookOrderItem) {
		// Basic mapping
		final BookOrderItemResource resource = bookOrderItemMapper.map(bookOrderItem);

		// adding hateoas links
		resource.add(linkTo(BookOrderItemController.class).slash(bookOrderItem.getBookOrderId()).slash(bookOrderItem.getBookId()).withSelfRel());
		return resource;
	}

}
