/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.BookController;
import org.demo.controller.mapper.BookMapper;
import org.demo.controller.resource.BookResource;
import org.demo.entity.Book;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class BookResourceAssembler extends ResourceAssemblerSupport<Book, BookResource> {

	// declare the mapper
	private BookMapper bookMapper;

	public BookResourceAssembler() {
		super(BookController.class, BookResource.class);
		bookMapper = Selma.builder(BookMapper.class).build();
	}

	@Override
	public BookResource toResource(Book book) {
		// Basic mapping
		final BookResource resource = bookMapper.map(book);
		resource.setId(book.getId());

		// adding hateoas links
		resource.add(linkTo(BookController.class).slash(book.getId()).withSelfRel());
		return resource;
	}

}
