/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.EmployeeGroupController;
import org.demo.controller.mapper.EmployeeGroupMapper;
import org.demo.controller.resource.EmployeeGroupResource;
import org.demo.entity.EmployeeGroup;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class EmployeeGroupResourceAssembler extends ResourceAssemblerSupport<EmployeeGroup, EmployeeGroupResource> {

	// declare the mapper
	private EmployeeGroupMapper employeeGroupMapper;

	public EmployeeGroupResourceAssembler() {
		super(EmployeeGroupController.class, EmployeeGroupResource.class);
		employeeGroupMapper = Selma.builder(EmployeeGroupMapper.class).build();
	}

	@Override
	public EmployeeGroupResource toResource(EmployeeGroup employeeGroup) {
		// Basic mapping
		final EmployeeGroupResource resource = employeeGroupMapper.map(employeeGroup);

		// adding hateoas links
		resource.add(linkTo(EmployeeGroupController.class).slash(employeeGroup.getEmployeeCode()).slash(employeeGroup.getGroupId()).withSelfRel());
		return resource;
	}

}
