/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.PublisherController;
import org.demo.controller.mapper.PublisherMapper;
import org.demo.controller.resource.PublisherResource;
import org.demo.entity.Publisher;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class PublisherResourceAssembler extends ResourceAssemblerSupport<Publisher, PublisherResource> {

	// declare the mapper
	private PublisherMapper publisherMapper;

	public PublisherResourceAssembler() {
		super(PublisherController.class, PublisherResource.class);
		publisherMapper = Selma.builder(PublisherMapper.class).build();
	}

	@Override
	public PublisherResource toResource(Publisher publisher) {
		// Basic mapping
		final PublisherResource resource = publisherMapper.map(publisher);

		// adding hateoas links
		resource.add(linkTo(PublisherController.class).slash(publisher.getCode()).withSelfRel());
		return resource;
	}

}
