/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.assembler;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;

import org.demo.controller.WorkgroupController;
import org.demo.controller.mapper.WorkgroupMapper;
import org.demo.controller.resource.WorkgroupResource;
import org.demo.entity.Workgroup;
import org.springframework.hateoas.mvc.ResourceAssemblerSupport;

import fr.xebia.extras.selma.Selma;

/**
 * Hateoas assembler class which make mapping and adding hateoas links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class WorkgroupResourceAssembler extends ResourceAssemblerSupport<Workgroup, WorkgroupResource> {

	// declare the mapper
	private WorkgroupMapper workgroupMapper;

	public WorkgroupResourceAssembler() {
		super(WorkgroupController.class, WorkgroupResource.class);
		workgroupMapper = Selma.builder(WorkgroupMapper.class).build();
	}

	@Override
	public WorkgroupResource toResource(Workgroup workgroup) {
		// Basic mapping
		final WorkgroupResource resource = workgroupMapper.map(workgroup);
		resource.setId(workgroup.getId());

		// adding hateoas links
		resource.add(linkTo(WorkgroupController.class).slash(workgroup.getId()).withSelfRel());
		return resource;
	}

}
