/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.test;
import static org.assertj.core.api.Assertions.assertThat;

import org.demo.controller.resource.AuthorResource;
import org.demo.entity.Author;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedResources;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.Sql.ExecutionPhase;
import org.springframework.test.context.jdbc.SqlGroup;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

// Junit specific runner
@RunWith(SpringJUnit4ClassRunner.class)
// Declare as spring boot test and define the port according to properties in
// src/test/resources/application.properties
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
// Ensure all are clean between two method test execution
@SqlGroup({ @Sql(executionPhase = ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:clean.sql") })
public class AuthorControllerTest {

	@Autowired
	private TestRestTemplate restTemplate;
	private static final String FIRSTNAME = "firstName";
	private static final String LASTNAME = "lastName";

	@Test
	public void createAuthorTest() {
		// Create an author
		Author author = createMocKAuthor(new Integer((int)1) , FIRSTNAME, LASTNAME);
		// Recover this author
		ResponseEntity<AuthorResource> result = this.restTemplate.getForEntity("/author/1", AuthorResource.class);
		// The response can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/author/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getFirstName()).isEqualTo(FIRSTNAME);
		assertThat(result.getBody().getLastName()).isEqualTo(LASTNAME);
		// Try to create the same author, must return a CONFLICT status code
		result = this.restTemplate.postForEntity("/author", author, AuthorResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
		// Response body must not be null
		assertThat(result.getBody()).isNull();
	}

	@Test
	public void updateTest() {
		// Create an author and assert field
		Author author = createMocKAuthor(new Integer((int)1)  , FIRSTNAME, LASTNAME);
		// Recover this author
		ResponseEntity<AuthorResource> result = this.restTemplate.getForEntity("/author/1", AuthorResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/author/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getFirstName()).isEqualTo(FIRSTNAME);
		assertThat(result.getBody().getLastName()).isEqualTo(LASTNAME);

		// Change field value
		author.setFirstName("firstName");
		author.setLastName("lastName");
		// Process update
		RequestEntity<Author> request = new RequestEntity<Author>(author, HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/author/1", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be OK
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Recover the author and ensure field are correct
		result = this.restTemplate.getForEntity("/author/1", AuthorResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		link = new Link("http://localhost:9999/author/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getFirstName()).isEqualTo("firstName");
		assertThat(result.getBody().getLastName()).isEqualTo("lastName");
	}

	@Test
	public void updateNotFoundTest() {
		// Process update
		RequestEntity<Author> request = new RequestEntity<Author>(new Author(), HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/author/999", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteTest() {
		// Create an author
		createMocKAuthor(new Integer((int)1)  , FIRSTNAME, LASTNAME);
		// Recover this author and test if all is ok
		ResponseEntity<AuthorResource> result = this.restTemplate.getForEntity("/author/1", AuthorResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Delete the author
		RequestEntity<Author> request = new RequestEntity<Author>(new Author(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/author/1", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_CONTENT
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);

		// Try to recover the author and ensure it's don't exist
		// Recover this author and test if all is ok
		result = this.restTemplate.getForEntity("/author/1", AuthorResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteNotFound() {
		// Delete the author
		RequestEntity<Author> request = new RequestEntity<Author>(new Author(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/author/999", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void getAuthorsTest() {
		// First call assert no element
		ResponseEntity<PagedResources<AuthorResource>> result = this.search("/author");
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		PagedResources<AuthorResource> page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata()).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(0);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(0);
		// By default page size is 20
		assertThat(page.getMetadata().getSize()).isEqualTo(20);

		// Insert 21 author
		for (int i = 1; i < 22; i++) {
			createMocKAuthor(new Integer((int)i),String.valueOf(i),String.valueOf(i));
		}
		result = this.search("/author");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(2);

		// Change the number of element per page and assert the page number
		result = this.search("/author?size=3");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(7);
	}

	@Test
	public void getAuthorsTestFilter() {
		// Create an author
		Author author = createMocKAuthor(new Integer((int)1) , FIRSTNAME, LASTNAME);
		RequestEntity<Author> request = null;
		ResponseEntity<PagedResources<AuthorResource>> result = null;
		PagedResources<AuthorResource> page = null;
		// Test firstName filter
		// Set the value on entity and update
		author.setFirstName("c");
		// Process update
		request = new RequestEntity<Author>(author, HttpMethod.PUT, null);
		this.restTemplate.exchange("/author/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test firstName filter
		result = this.search("/author?size=20&firstName=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (AuthorResource authorResource : page.getContent()) {
			assertThat(authorResource.getFirstName()).startsWith("c");
		}
		// Test lastName filter
		// Set the value on entity and update
		author.setLastName("c");
		// Process update
		request = new RequestEntity<Author>(author, HttpMethod.PUT, null);
		this.restTemplate.exchange("/author/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test lastName filter
		result = this.search("/author?size=20&lastName=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (AuthorResource authorResource : page.getContent()) {
			assertThat(authorResource.getLastName()).startsWith("c");
		}
	}

	private Author createMocKAuthor(Integer id, String firstName, String lastName) {
		Author authorMock = new Author();
		authorMock.setId(id);
		authorMock.setFirstName(firstName);
		authorMock.setLastName(lastName);
		this.restTemplate.postForLocation("/author", authorMock);
		return authorMock;
	}

	private ResponseEntity<PagedResources<AuthorResource>> search(String uri) {
		return this.restTemplate.exchange(uri, HttpMethod.GET, null, getTypeRef());
	}

	private ParameterizedTypeReference<PagedResources<AuthorResource>> getTypeRef() {
		return new ParameterizedTypeReference<PagedResources<AuthorResource>>() {
		};
	}

	private ParameterizedTypeReference<Void> getTypeRefVoid() {
		return new ParameterizedTypeReference<Void>() {
		};
	}
}