/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.test;
import static org.assertj.core.api.Assertions.assertThat;

import org.demo.controller.resource.EmployeeGroupResource;
import org.demo.entity.EmployeeGroup;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedResources;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.Sql.ExecutionPhase;
import org.springframework.test.context.jdbc.SqlGroup;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

// Junit specific runner
@RunWith(SpringJUnit4ClassRunner.class)
// Declare as spring boot test and define the port according to properties in
// src/test/resources/application.properties
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
// Ensure all are clean between two method test execution
@SqlGroup({ @Sql(executionPhase = ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:clean.sql") })
public class EmployeeGroupControllerTest {

	@Autowired
	private TestRestTemplate restTemplate;

	@Test
	public void createEmployeeGroupTest() {
		// Create an employeeGroup
		EmployeeGroup employeeGroup = createMocKEmployeeGroup("1" ,new Short((short)1) );
		// Recover this employeeGroup
		ResponseEntity<EmployeeGroupResource> result = this.restTemplate.getForEntity("/employeeGroup/1/1", EmployeeGroupResource.class);
		// The response can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/employeeGroup/1/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		// Try to create the same employeeGroup, must return a CONFLICT status code
		result = this.restTemplate.postForEntity("/employeeGroup", employeeGroup, EmployeeGroupResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
		// Response body must not be null
		assertThat(result.getBody()).isNull();
	}

	@Test
	public void updateTest() {
		// Create an employeeGroup and assert field
		EmployeeGroup employeeGroup = createMocKEmployeeGroup("1" ,new Short((short)1)  );
		// Recover this employeeGroup
		ResponseEntity<EmployeeGroupResource> result = this.restTemplate.getForEntity("/employeeGroup/1/1", EmployeeGroupResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/employeeGroup/1/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);

		// Change field value
		// Process update
		RequestEntity<EmployeeGroup> request = new RequestEntity<EmployeeGroup>(employeeGroup, HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/employeeGroup/1/1", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be OK
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Recover the employeeGroup and ensure field are correct
		result = this.restTemplate.getForEntity("/employeeGroup/1/1", EmployeeGroupResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		link = new Link("http://localhost:9999/employeeGroup/1/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
	}

	@Test
	public void updateNotFoundTest() {
		// Process update
		RequestEntity<EmployeeGroup> request = new RequestEntity<EmployeeGroup>(new EmployeeGroup(), HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/employeeGroup/999/999", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteTest() {
		// Create an employeeGroup
		createMocKEmployeeGroup("1" ,new Short((short)1)  );
		// Recover this employeeGroup and test if all is ok
		ResponseEntity<EmployeeGroupResource> result = this.restTemplate.getForEntity("/employeeGroup/1/1", EmployeeGroupResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Delete the employeeGroup
		RequestEntity<EmployeeGroup> request = new RequestEntity<EmployeeGroup>(new EmployeeGroup(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/employeeGroup/1/1", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_CONTENT
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);

		// Try to recover the employeeGroup and ensure it's don't exist
		// Recover this employeeGroup and test if all is ok
		result = this.restTemplate.getForEntity("/employeeGroup/1/1", EmployeeGroupResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteNotFound() {
		// Delete the employeeGroup
		RequestEntity<EmployeeGroup> request = new RequestEntity<EmployeeGroup>(new EmployeeGroup(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/employeeGroup/999/999", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void getEmployeeGroupsTest() {
		// First call assert no element
		ResponseEntity<PagedResources<EmployeeGroupResource>> result = this.search("/employeeGroup");
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		PagedResources<EmployeeGroupResource> page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata()).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(0);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(0);
		// By default page size is 20
		assertThat(page.getMetadata().getSize()).isEqualTo(20);

		// Insert 21 employeeGroup
		for (int i = 1; i < 22; i++) {
			createMocKEmployeeGroup(String.valueOf(i), new Short((short)i));
		}
		result = this.search("/employeeGroup");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(2);

		// Change the number of element per page and assert the page number
		result = this.search("/employeeGroup?size=3");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(7);
	}


	private EmployeeGroup createMocKEmployeeGroup(String employeeCode,Short groupId) {
		EmployeeGroup employeeGroupMock = new EmployeeGroup();
		employeeGroupMock.setEmployeeCode(employeeCode);
		employeeGroupMock.setGroupId(groupId);
		this.restTemplate.postForLocation("/employeeGroup", employeeGroupMock);
		return employeeGroupMock;
	}

	private ResponseEntity<PagedResources<EmployeeGroupResource>> search(String uri) {
		return this.restTemplate.exchange(uri, HttpMethod.GET, null, getTypeRef());
	}

	private ParameterizedTypeReference<PagedResources<EmployeeGroupResource>> getTypeRef() {
		return new ParameterizedTypeReference<PagedResources<EmployeeGroupResource>>() {
		};
	}

	private ParameterizedTypeReference<Void> getTypeRefVoid() {
		return new ParameterizedTypeReference<Void>() {
		};
	}
}