/*
 * Created on 2017-12-20 ( Date ISO 2017-12-20 - Time 14:58:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.repository;

import org.demo.entity.EmployeeGroup;
import org.demo.entity.EmployeeGroupKey;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for EmployeeGroup.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface EmployeeGroupRepository  extends JpaRepository<EmployeeGroup, EmployeeGroupKey>, JpaSpecificationExecutor<EmployeeGroup> {}